In [22]:
#Ensemble methods

import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import model_selection


In [8]:
df=pd.read_csv(r"C:\Users\FX505DT\Downloads\letters_ABPR.csv")

print(df.shape)
df.head(10)

(3116, 17)


letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
0      B     4     2      5       4      4     8     7      6      6      7   
1      A     1     1      3       2      1     8     2      2      2      8   
2      R     5     9      5       7      6     6    11      7      3      7   
3      B     5     9      7       7     10     9     8      4      4      6   
4      P     3     6      4       4      2     4    14      8      1     11   
5      R     8    10      8       6      6     7     7      3      5      8   
6      R     2     6      4       4      3     6     7      5      5      6   
7      A     3     7      5       5      3    12     2      3      2     10   
8      P     8    14      7       8      4     5    10      6      3     12   
9      P     6    10      8       8      7     8     5      7      5      7   

   x2ybar  xy2bar  xedge  xedgeycor  yedge  yedgexcor  
0       6       6      2          8      7         10  
1       2       8      1          6      2          7  
2       3       9      2          7      5         11  
3       8       6      6         11      8          7  
4       6       3      0         10      4          8  
5       4       8      6          6      7          7  
6       5       7      3          7      5          8  
7       2       9      2          6      3          8  
8       5       4      4         10      4          8  
9       6       6      3          9      8          9

In [12]:
y = df["letter"].values
x = df.drop('letter',axis=1).values

In [13]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [17]:
logreg = LogisticRegression()

logreg.fit(X_train,y_train)

y_pred = logreg.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[236   0   1   4]
 [  0 217   0  14]
 [  1   4 222   4]
 [  2  19   3 208]]
              precision    recall  f1-score   support

           A       0.99      0.98      0.98       241
           B       0.90      0.94      0.92       231
           P       0.98      0.96      0.97       231
           R       0.90      0.90      0.90       232

    accuracy                           0.94       935
   macro avg       0.94      0.94      0.94       935
weighted avg       0.94      0.94      0.94       935



C:\Users\FX505DT\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [27]:
# Bagging
kfold = model_selection.KFold(n_splits=10)

model_bag = BaggingClassifier(base_estimator=DecisionTreeClassifier(),
                              n_estimators=100)

results_bag = model_selection.cross_val_score(model_bag, x, y, cv=kfold)
print(results_bag.mean())

0.9714413801632451


In [30]:
# RandomForest

model_rf = RandomForestClassifier(n_estimators=50,max_features=5)

results_rf = model_selection.cross_val_score(model_bag, x, y, cv=kfold)
print(results_rf.mean())

0.9704798417017066


In [31]:
# Boosting
from sklearn.ensemble import AdaBoostClassifier
model_ada = AdaBoostClassifier(n_estimators=50)

results_ada = model_selection.cross_val_score(model_ada, x, y, cv=kfold)
print(results_ada.mean())

0.8443338280155
